routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/check_command','Lock\LockController@checkCommand');
Route::post('/make_response','Lock\LockController@makeResponse')->name('make_response');
Route::post('/create_lock','Lock\LockController@createLock')->name('create_lock');
Route::post('/delete_lock','Lock\LockController@deleteLock')->name('delete_lock');
//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Admin\PagesController@index');
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/dashboard/{date?}', 'Admin\PagesController@welcome')->name('dashboard');

    Route::prefix('bikes')->name('bikes.')->group(function () {
        Route::get('/', 'Admin\BikeController@getBikes')->name('index');
        Route::get('/add_bike', 'Admin\BikeController@getAddBike')->name('add')->middleware('checkadmin');
        Route::post('/add_bike_p', 'Admin\BikeController@addBike')->name('add_p')->middleware('checkadmin');
        Route::get('/bike/{bike_id}', 'Admin\BikeController@editBike')->name('edit');
        Route::post('/edit/{bike_id}', 'Admin\BikeController@makeBikeChanges')->name('edit_p')->middleware('checkadmin');
        Route::get('/delete/{bike_id}', 'Admin\BikeController@deleteBike')->name('delete')->middleware('checkadmin');
    });
    Route::prefix('models')->middleware('checkadmin')->name('models.')->group(function () {
        Route::get('/', 'Admin\BikeModelController@getModels')->name('index');
        Route::get('/edit/{edit_id}', 'Admin\BikeModelController@editModel')->name('edit');
        Route::post('/model/{edit_id}', 'Admin\BikeModelController@makeModelChanges')->name('edit_p');
        Route::get('/add_model', 'Admin\BikeModelController@getAddModel')->name('add');
        Route::post('/add_model_p', 'Admin\BikeModelController@addModel')->name('add_p');
        Route::get('/delete/{delete_id}', 'Admin\BikeModelController@deleteModel')->name('delete');
    });
    Route::prefix('types')->middleware('checkadmin')->name('types.')->group(function () {
        Route::get('/', 'Admin\BikeTypeController@getTypes')->name('index');
        Route::get('/edit/{edit_id}', 'Admin\BikeTypeController@editType')->name('edit');
        Route::post('/type/{edit_id}', 'Admin\BikeTypeController@makeTypeChanges')->name('edit_p');
        Route::get('/add_type', 'Admin\BikeTypeController@getAddType')->name('add');
        Route::post('/add_type_p', 'Admin\BikeTypeController@addType')->name('add_p');
        Route::get('/delete/{delete_id}', 'Admin\BikeTypeController@deleteType')->name('delete');
    });
    Route::prefix('parkings')->name('parkings.')->group(function () {
        Route::get('/', 'Admin\ParkingController@getParkings')->name('index');
        Route::get('/add_parking', 'Admin\ParkingController@getAddParking')->name('add')->middleware('checkadmin');
        Route::post('/add_parking_p', 'Admin\ParkingController@addParking')->name('add_p')->middleware('checkadmin');
        Route::get('/parking/{parking_id}', 'Admin\ParkingController@editParking')->name('edit');
        Route::post('/edit/{parking_id}', 'Admin\ParkingController@makeParkingChanges')->name('edit_p')->middleware('checkadmin');
        Route::get('/delete/{parking_id}', 'Admin\ParkingController@deleteParking')->name('delete')->middleware('checkadmin');
    });
    Route::prefix('clients')->name('clients.')->group(function () {
        Route::get('/', 'Admin\ClientController@getClients')->name('index');
        Route::get('/add_client', 'Admin\ClientController@getAddClient')->name('add')->middleware('checkadmin');
        Route::post('/add_client_p', 'Admin\ClientController@addClient')->name('add_p')->middleware('checkadmin');
        Route::get('/client/{client_id}', 'Admin\ClientController@editClient')->name('edit')->middleware('checkadmin');
        Route::get('/delete/{client_id}', 'Admin\ClientController@deleteClient')->name('delete')->middleware('checkadmin');
        Route::get('/info/{client_id}', 'Admin\ClientController@getClientInfo')->name('info');
        Route::post('/client/{client_id}', 'Admin\ClientController@makeClientChanges')->name('edit_p')->middleware('checkadmin');
    });
    Route::prefix('trips')->name('trips.')->group(function () {
        Route::get('/', 'Admin\TripController@getTrips')->name('index');
        Route::get('/info/{trip_id}', 'Admin\TripController@getTripInfo')->name('info');
    });
    Route::prefix('payments')->name('payments.')->group(function () {
        Route::get('/', 'Admin\PaymentController@getFinances')->name('index');
    });
    Route::prefix('tickets')->name('tickets.')->group(function () {
        Route::get('/', 'Admin\TicketController@getTickets')->name('index');
        Route::get('/ticket/{ticket_id}', 'Admin\TicketController@getTicket')->name('info');
        Route::get('/changestatus/{ticket_id}/{status_id}', 'Admin\TicketController@changeStatus')->name('changestatus');
        Route::post('/send_message/{ticket_id}', 'Admin\TicketController@sendMessage')->name('send_message');
    });
    Route::prefix('tarifs')->name('tarifs.')->middleware('checkadmin')->group(function () {
        Route::get('/', 'Admin\TarifController@getTarifs')->name('index');
        Route::post('/tarif/{tarif_id}', 'Admin\TarifController@changeTarif')->name('change');
    });
    Route::prefix('promocodes')->middleware('checkadmin')->name('promocodes.')->group(function () {
        Route::get('/add_promocode', 'Admin\PromocodeController@getCreatePromocode')->name('add');
        Route::post('/add_promocode_p', 'Admin\PromocodeController@createPromocode')->name('add_p');
    });
    Route::prefix('promoactions')->middleware('checkadmin')->name('promoactions.')->group(function () {
        Route::get('/', 'Admin\PromoactionController@getPromoactions')->name('index');
        Route::get('/add_promoaction', 'Admin\PromoactionController@getAddPromoaction')->name('add');
        Route::post('/add_promoaction_p', 'Admin\PromoactionController@addPromoaction')->name('add_p');
        Route::get('/promoaction/{promoaction_id}', 'Admin\PromoactionController@editPromoaction')->name('edit');
        Route::post('/edit/{promoaction_id}', 'Admin\PromoactionController@makePromoactionChanges')->name('edit_p');
        Route::get('/delete/{promoaction_id}', 'Admin\PromoactionController@deletePromoaction')->name('delete');
    });
    Route::prefix('users')->middleware('checkadmin')->name('users.')->group(function () {
        Route::get('/', 'Admin\UserController@getUsers')->name('index');
        Route::get('/add_user', 'Admin\UserController@getAddUser')->name('add');
        Route::post('/add_user_p', 'Admin\UserController@addUser')->name('add_p');
        Route::get('/user/{user_id}', 'Admin\UserController@editUser')->name('edit');
        Route::get('/delete/{user_id}', 'Admin\UserController@deleteUser')->name('delete');
        Route::get('/info/{user_id}', 'Admin\UserController@getUserInfo')->name('info');
        Route::post('/user/{user_id}', 'Admin\UserController@makeUserChanges')->name('edit_p');
    });
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class Client extends Authenticatable
{
    use Notifiable, SoftDeletes, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];
    protected $hidden = [
        'vote_type',
        'email_verified_at',
        'is_vote',
        'additional'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $dates = ['deleted_at'];

    public function trips()
    {
        return $this->hasMany('App\Trip');
    }

    public function booking()
    {
        return $this->hasMany('App\Booking');
    }
    public function tickets()
    {
        return $this->hasMany('App\Ticket');
    }

    public function payments()
    {
        return $this->hasMany('App\Payment');
    }

    public function promocodes()
    {
        return $this->hasMany('App\Promocode');
    }

    public function verification()
    {
        return $this->hasOne('App\Verification');
    }

    public function reports()
    {
        return $this->hasMany('App\Report');
    }

    public function promoactions()
    {
        return $this->belongsToMany('App\Promoaction');
    }

    public function pledge()
    {
        return $this->hasOne('App\Pledge');
    }
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;

class ClientController extends Controller
{
    public function getClients()
    {
        $search = $this->searchClients();
        if ($search !== 0) {
            return $search;
        }
        $route_name = Route::currentRouteName();
        $title = 'Пользователи';
        $clients = Client::orderBy('id','desc')->paginate(15);
        return view('admin.clients.list',compact('route_name','title','clients'));

    }

    public function getAddClient()
    {
        $route_name = Route::currentRouteName();
        $title = 'Добавить пользователя';
        return view('admin.clients.form',compact('route_name','title'));
    }

    public function addClient(Request $request)
    {
        $request->validate([
            'surname'=>'required',
            'name'=>'required',
            'sex_id'=>'required',
            'phone'=>'required|unique:clients',
            'verificated'=>'required',
            'is_locked'=>'required',
            'growth'=>'required|numeric',
            'weight'=>'required|numeric',
            'email'=>'required|email|unique:clients',
            'birthdate'=>'required|date'
        ]);
        Client::create($request->all());
        return redirect('/admin/clients');
    }

    public function editClient($client_id)
    {
        $route_name = Route::currentRouteName();
        $title = 'Редактировать пользователя';
        $client = Client::find($client_id);
        return view('admin.clients.form',compact('route_name','title', 'client'));
    }

    public function makeClientChanges(Request $request, $client_id)
    {
        $request->validate([
            'surname'=>'required',
            'name'=>'required',
            'sex_id'=>'required',
            'verificated'=>'required',
            'is_locked'=>'required',
            'growth'=>'required|numeric',
            'weight'=>'required|numeric',
            'birthdate'=>'required|date'
        ]);
        $client = Client::find($client_id);
        if ($client->phone != $request->input('phone')) {
            $request->validate([
                'phone'=>'required|unique:clients'
            ]);
        }
        if ($client->email != $request->input('email')) {
            $request->validate([
                'email'=>'required|email|unique:clients',
            ]);
        }
        $client->update($request->except('birthdate'));
        $birthdate = date('Y-m-d', strtotime($request->input('birthdate')));
        $client->update(compact('birthdate'));
        return redirect()->back();
    }

    public function getClientInfo($client_id)
    {
        $route_name = Route::currentRouteName();
        $title = 'Информация о клиенте';
        $client = Client::find($client_id);
        $payments = $client->payments;
        $client->payments_amount = 0;
        foreach ($payments as $payment) {
            $client->payments_amount += $payment->amount;
        }
        $trips = $client->trips()->orderBy('id', "desc")->paginate(15);
        $payments = $client->payments()->orderBy('id', "desc")->paginate(15);
        return view('admin.clients.info', compact('route_name','title','client','trips','payments'));
    }

    public function deleteClient($client_id)
    {
        $client = Client::find($client_id);
        $client->delete();
        return redirect('/admin/clients');
    }
    private function searchClients()
    {
        if (isset($_GET['search_client']))
        {
            $search = trim(urldecode($_GET['search_client']));
            if (empty($search)) {
                $clients = Client::orderBy('id','desc')->paginate(15);
            }
            else {
                $clients = Client::orWhere('id', 'LIKE', "%{$search}%")
                    ->orWhere('phone', 'LIKE', "%{$search}%")
                    ->orWhere('surname', 'LIKE', "%{$search}%")
                    ->orWhere('name', 'LIKE', "%{$search}%")
                    ->orWhere('email', 'LIKE', "%{$search}%")
                    ->get();
            }
            if ((stripos($search, 'акт'))) {
                $clients = Client::where('is_locked', 0)->get();
            }

            if ((stripos($search, 'забл'))) {
                $clients = Client::where('is_locked', 1)->get();
            }
            $clients = $this->makeClients($clients);
            return view('admin.clients.table', compact('clients'));
        }
        return 0;
    }

    private function makeClients($clients)
    {
        foreach ($clients as $client) {
            if (!empty($client->birthdate)) {
                $client->birthdate = date('d.m.Y', strtotime($client->birthdate));
            }
        }
        return $clients;
    }
}

resources/views/admin/clients/form.blade.php
@extends("admin.layouts.layout")
@section("content")
	<div class="container">
		<ul class="breadcrumbs">
			<li><a href="{{route('admin.dashboard')}}" title="Главная">Главная</a></li>
			<li>{{ $title }}</li>
		</ul>
		<div class="clearfix"></div>
		<div class="header">
			<h1>{{ $title }}</h1>
		</div>
		<div class="clearfix"></div>
		@if (isset($client))
			<form action="{{ route('admin.clients.edit_p', ['client_id'=>$client->id]) }}" method="post">
		@else
			<form action="{{ route('admin.clients.add_p') }}" method="post">
		@endif
			@csrf
			<div class="row">
				<div class="col-md-12">
					@if (isset($errors))
						@foreach($errors->all() as $error)
							<div class="alert alert-warning">{{ $error }}</div>
						@endforeach
					@endif
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label for="user_sur">Фамилия</label>
						<input id="user_sur" type="text" name="surname" value="@if (isset($client)) {{ $client->surname }} @else {{old('surname')}}@endif" class="form-control">
					</div>
					<div class="form-group">
						<label for="user_name">Имя</label>
						<input id="user_name" type="text" name="name" value="@if (isset($client)) {{ $client->name }} @else {{old('name')}}@endif" class="form-control">
					</div>
					<div class="form-group">
						<label for="user_dob">Дата рождения ДД.ММ.ГГГГ</label>
						<input id="user_dob" type="text" name="birthdate" value="@if (isset($client)){{ date('d.m.Y',strtotime($client->birthdate)) }} @else {{old('birthdate')}}@endif" class="form-control">
					</div>
					<div class="form-group">
						<label for="user_sex">Пол</label>
						<select id="user_sex" name="sex_id" class="form-control">
							<option value="">Выберите</option>
							<option value="1" @if (isset($client)) @if ($client->sex_id == 1) selected @endif @endif>Мужской</option>
							<option value="2" @if (isset($client)) @if ($client->sex_id == 2) selected @endif @endif>Женский</option>
						</select> 
					</div>
					<div class="form-group">
						<label for="user_phone">Телефон</label>
						<input id="user_phone" type="text" name="phone" value="@if (isset($client)) {{ $client->phone }} @else {{old('phone')}}@endif" class="form-control">
					</div>

				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label for="user_email">E-mail</label>
						<input id="user_email" type="email" name="email" value="@if (isset($client)) {{ $client->email }} @else {{old('email')}}@endif" class="form-control">
					</div>
					<div class="form-group">
						<label for="user_growth">Рост</label>
						<input id="user_growth" type="text" name="growth" value="@if (isset($client)) {{ $client->growth }} @else {{old('growth')}}@endif" class="form-control">
					</div>
					<div class="form-group">
						<label for="user_weight">Вес</label>
						<input id="user_weight" type="text" name="weight" value="@if (isset($client)) {{ $client->weight }} @else {{old('weight')}}@endif" class="form-control">
					</div>
					<div class="form-group">
						<label for="user_ver">Аккаунт подтвержден (верификация)</label>
						<select id="user_ver" name="verificated" class="form-control">
							<option value="0" @if (isset($client)) @if ($client->verificated == 0) selected @endif @endif>Нет</option>
							<option value="1" @if (isset($client)) @if ($client->verificated == 1) selected @endif @endif>Да</option>
						</select> 	
					</div>
					<div class="form-group">
						<label for="user_lock">Аккаунт заблокирован</label>
						<select id="user_lock" name="is_locked" class="form-control">
							<option value="0" @if (isset($client)) @if ($client->is_locked == 0) selected @endif @endif>Нет</option>
							<option value="1" @if (isset($client)) @if ($client->is_locked == 1) selected @endif @endif>Да</option>
						</select> 
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<label for="user_memo">Дополнительная информация</label>
					<textarea id="user_memo" name="additional" rows="5" class="form-control">@if (isset($client)) {{ $client->additional }} @else {{old('additional')}}@endif</textarea>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<br>
					<div class="form-group">
						<input type="submit" value="{{ $title }}" class="form-control btn btn-primary">
					</div>		 			
				</div>
			</div>
			@if (isset($client))
				</form>
			@else
				</form>
		@endif
	</div>
@endsection

resources/views/admin/clients/info.blade.php
@extends("admin.layouts.layout")
@section("content")
	<div class="container">
		<ul class="breadcrumbs">
			<li><a href="{{route('admin.dashboard')}}" title="Главная">Главная</a></li>
			<li>Карточка пользователя</li>
		</ul>
		<div class="clearfix"></div>
		<div class="header">
			<h1>Карточка пользователя</h1>
			<ul class="buttons">
				<li><a href="#" class="a_tab active" data-tab="info">Информация о пользователе</a></li>
				<li><a href="#" data-tab="trips" class="a_tab">Все поездки</a></li>
				<li><a href="#" data-tab="finance" class="a_tab">Финансовые операции</a></li>
			</ul>
		</div>
	</div>
	<div class="container">
		<div class="atab atab_info">
			<div class="row user">
				<div class="col-md-4">
					<img src="{{$client->photo? url('storage/avatars/'.$client->photo):'http://weedoo.ru/public/img/ava_user.png'}}" style="width:370px; height: auto" >
					<ul class="buttons">
						<li><a href="{{route('admin.clients.edit',['client_id'=>$client->id])}}" class="active">Редактировать</a></li>
						<li style="float: right;"><a href="{{route('admin.clients.delete',['client_id'=>$client->id])}}" class="active" >Удалить</a></li>
					</ul>
				</div>
				<div class="col-md-8">
					<table class="user">
					<tr>
						<td>ID</td>
						<td>{{ $client->id }}</td>
					</tr>
					<tr>
						<td>Имя</td>
						<td>{{ $client->name }}</td>
					</tr>
					<tr>
						<td>Фамилия</td>
						<td>{{ $client->surname }}</td>
					</tr>
					<tr>
						<td>Email</td>
						<td>{{ $client->email }}</td>
					</tr>
					<tr>
						<td>Телефон</td>
						<td>{{ $client->phone }}</td>
					</tr>
					<tr>
						<td>Дата/мес/год рожд</td>
						<td>{{ $client->birthdate }}</td>
					</tr>
					<tr>
						<td>Рост</td>
						<td>{{ $client->growth }}</td>
					</tr>
					<tr>
						<td>Вес</td>
						<td>{{ $client->weight }}</td>
					</tr>
					<tr>
						<td>Дата время регистрации</td>
						<td>{{date('H:i d.m.Y',strtotime($client->created_at))}}</td>
					</tr>
					<tr>
						<td>Дата посл. входа</td>
						<td>{{date('H:i d.m.Y', strtotime($client->lastvisit))}}</td>
					</tr>
					<tr>
						<td>Статус</td>
						<td>
							@if ($client->is_locked)
								Заблокирован
							@else
								Активен
							@endif
						</td>
					</tr>
					<tr>
						<td>Баланс</td>
						<td>{{$client->balance}}</td>
					</tr>
					<tr>
						<td>Сумма оплат</td>
						<td>{{$client->payments_amount}}</td>
					</tr>
					<tr>
						<td>Пол</td>
						<td>
							@if ($client->sex_id)
								Мужской
							@else
								Женский
							@endif
						</td>
					</tr>
					<tr>
						<td>Верификация</td>
						<td>
							@if ($client->verificated)
								Верифицирован
							@else
								Не верифицирован
							@endif
						</td>
					</tr>
					<tr>
						<td>Социальный статус</td>
						<td>&mdash;</td>
					</tr>
					<tr>
						<td>Наличие залога</td>
						<td>&mdash;
						@if($client->pledge)
							Да
						@else
							Нет
						@endif
						</td>
					</tr>
					<tr>
						<td>Количество активированных промокодов</td>
						<td>&mdash;{{$client->promocodes? $client->promocodes()->count():0 }}</td>
					</tr>
					</table>
				</div>
			</div>
		</div>
		<div class="atab atab_trips" style="display: none;">
			@include('admin.trips.table')
            {{$trips->links('admin.layouts.pagination')}}
		</div>
		<div class="atab atab_finance" style="display: none;">
			@include('admin.payments.table')
            {{$payments->links('admin.layouts.pagination')}}
		</div>
	</div>
@endsection
@section("js")
	<script>
		$(document).ready(function() {
			$('.a_tab').click(function() {
				this_tab = $(this).data('tab');
				this_t = $('.atab_'+this_tab);
				if (!this_t.length) {					
					return false;
				}
				$('.a_tab').removeClass('active');
				$(this).addClass('active');
				$('.atab').fadeOut('fast');
				$(this_t).fadeIn('fast');
			});
			
		});
	</script>
@endsection

resources/views/admin/clients/list.blade.php
@extends("admin.layouts.layout")
@section("content")
	<div class="container">
		<ul class="breadcrumbs">
			<li><a href="{{route('admin.dashboard')}}" title="Главная">Главная</a></li>
			<li>Пользователи сервиса</li>
		</ul>
		<div class="clearfix"></div>
		<div class="header">
			<h1>Пользователи сервиса</h1>
		</div>
		<ul class="buttons">
			<li><a href="{{route('admin.clients.add')}}">Добавить пользователя</a></li>
			<li><a href="{{route('admin.users.index')}}">Менеджеры сервиса</a></li>
		</ul>
	</div>
	
	<div class="container" style="margin-top: 20px;">
		<input id="search" class="form-control input-lg" type="text" placeholder="Начните вводить...">
	</div>
	<div class="container">
		<div id="search-result">
			@include("admin.clients.table")
		</div>
		{{$clients->links('admin.layouts.pagination')}}
	</div>
@endsection
@section("js")
	<script type="text/javascript">
        $('#search').on('input change', function (e) {
            e.preventDefault();

            $.ajax({
                url: "{{route('admin.clients.index')}}",
                type: "GET",
                data: {search_client: $(this).val()},
                success: function (res) {
                    $('#search-result').html(res);
                }
            });
        });
	</script>
@endsection

resources/views/admin/clients/table.blade.php
<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Email</th>
        <th scope="col">Телефон</th>
        <th scope="col">Дата рожд</th>
        <th scope="col">Статус</th>
        <th scope="col">Баланс</th>
        <th scope="col">Кол. поездок</th>
    </tr>
    </thead>
    <tbody id="search-table">
    @foreach ($clients as $client)
        <tr>
            <th scope="row"><a href="{{route('admin.clients.info',['client_id'=>$client->id])}}">{{ $client->id }}</a></th>
            <td>{{ $client->name }}</td>
            <td>{{ $client->surname }}</td>
            <td>{{ $client->email }}</td>
            <td>{{ $client->phone }}</td>
            <td>{{ date('d.m.Y',strtotime($client->birthdate ))}}</td>
            <td>
                @if ($client->id_locked)
                    Заблокирован
                @else
                    Активен
                @endif
            </td>
            <td>{{$client->balance?$client->balance:0}} руб.</td>
            <td>{{$client->trips()? $client->trips()->where('done', 1)->count():0}}</td>
        </tr>
    @endforeach
    </tbody>
</table>