routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/check_command','Lock\LockController@checkCommand');
Route::post('/make_response','Lock\LockController@makeResponse')->name('make_response');
Route::post('/create_lock','Lock\LockController@createLock')->name('create_lock');
Route::post('/delete_lock','Lock\LockController@deleteLock')->name('delete_lock');
//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Admin\PagesController@index');
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/dashboard/{date?}', 'Admin\PagesController@welcome')->name('dashboard');

    Route::prefix('bikes')->name('bikes.')->group(function () {
        Route::get('/', 'Admin\BikeController@getBikes')->name('index');
        Route::get('/add_bike', 'Admin\BikeController@getAddBike')->name('add')->middleware('checkadmin');
        Route::post('/add_bike_p', 'Admin\BikeController@addBike')->name('add_p')->middleware('checkadmin');
        Route::get('/bike/{bike_id}', 'Admin\BikeController@editBike')->name('edit');
        Route::post('/edit/{bike_id}', 'Admin\BikeController@makeBikeChanges')->name('edit_p')->middleware('checkadmin');
        Route::get('/delete/{bike_id}', 'Admin\BikeController@deleteBike')->name('delete')->middleware('checkadmin');
    });
    Route::prefix('models')->middleware('checkadmin')->name('models.')->group(function () {
        Route::get('/', 'Admin\BikeModelController@getModels')->name('index');
        Route::get('/edit/{edit_id}', 'Admin\BikeModelController@editModel')->name('edit');
        Route::post('/model/{edit_id}', 'Admin\BikeModelController@makeModelChanges')->name('edit_p');
        Route::get('/add_model', 'Admin\BikeModelController@getAddModel')->name('add');
        Route::post('/add_model_p', 'Admin\BikeModelController@addModel')->name('add_p');
        Route::get('/delete/{delete_id}', 'Admin\BikeModelController@deleteModel')->name('delete');
    });
    Route::prefix('types')->middleware('checkadmin')->name('types.')->group(function () {
        Route::get('/', 'Admin\BikeTypeController@getTypes')->name('index');
        Route::get('/edit/{edit_id}', 'Admin\BikeTypeController@editType')->name('edit');
        Route::post('/type/{edit_id}', 'Admin\BikeTypeController@makeTypeChanges')->name('edit_p');
        Route::get('/add_type', 'Admin\BikeTypeController@getAddType')->name('add');
        Route::post('/add_type_p', 'Admin\BikeTypeController@addType')->name('add_p');
        Route::get('/delete/{delete_id}', 'Admin\BikeTypeController@deleteType')->name('delete');
    });
    Route::prefix('parkings')->name('parkings.')->group(function () {
        Route::get('/', 'Admin\ParkingController@getParkings')->name('index');
        Route::get('/add_parking', 'Admin\ParkingController@getAddParking')->name('add')->middleware('checkadmin');
        Route::post('/add_parking_p', 'Admin\ParkingController@addParking')->name('add_p')->middleware('checkadmin');
        Route::get('/parking/{parking_id}', 'Admin\ParkingController@editParking')->name('edit');
        Route::post('/edit/{parking_id}', 'Admin\ParkingController@makeParkingChanges')->name('edit_p')->middleware('checkadmin');
        Route::get('/delete/{parking_id}', 'Admin\ParkingController@deleteParking')->name('delete')->middleware('checkadmin');
    });
    Route::prefix('clients')->name('clients.')->group(function () {
        Route::get('/', 'Admin\ClientController@getClients')->name('index');
        Route::get('/add_client', 'Admin\ClientController@getAddClient')->name('add')->middleware('checkadmin');
        Route::post('/add_client_p', 'Admin\ClientController@addClient')->name('add_p')->middleware('checkadmin');
        Route::get('/client/{client_id}', 'Admin\ClientController@editClient')->name('edit')->middleware('checkadmin');
        Route::get('/delete/{client_id}', 'Admin\ClientController@deleteClient')->name('delete')->middleware('checkadmin');
        Route::get('/info/{client_id}', 'Admin\ClientController@getClientInfo')->name('info');
        Route::post('/client/{client_id}', 'Admin\ClientController@makeClientChanges')->name('edit_p')->middleware('checkadmin');
    });
    Route::prefix('trips')->name('trips.')->group(function () {
        Route::get('/', 'Admin\TripController@getTrips')->name('index');
        Route::get('/info/{trip_id}', 'Admin\TripController@getTripInfo')->name('info');
    });
    Route::prefix('payments')->name('payments.')->group(function () {
        Route::get('/', 'Admin\PaymentController@getFinances')->name('index');
    });
    Route::prefix('tickets')->name('tickets.')->group(function () {
        Route::get('/', 'Admin\TicketController@getTickets')->name('index');
        Route::get('/ticket/{ticket_id}', 'Admin\TicketController@getTicket')->name('info');
        Route::get('/changestatus/{ticket_id}/{status_id}', 'Admin\TicketController@changeStatus')->name('changestatus');
        Route::post('/send_message/{ticket_id}', 'Admin\TicketController@sendMessage')->name('send_message');
    });
    Route::prefix('tarifs')->name('tarifs.')->middleware('checkadmin')->group(function () {
        Route::get('/', 'Admin\TarifController@getTarifs')->name('index');
        Route::post('/tarif/{tarif_id}', 'Admin\TarifController@changeTarif')->name('change');
    });
    Route::prefix('promocodes')->middleware('checkadmin')->name('promocodes.')->group(function () {
        Route::get('/add_promocode', 'Admin\PromocodeController@getCreatePromocode')->name('add');
        Route::post('/add_promocode_p', 'Admin\PromocodeController@createPromocode')->name('add_p');
    });
    Route::prefix('promoactions')->middleware('checkadmin')->name('promoactions.')->group(function () {
        Route::get('/', 'Admin\PromoactionController@getPromoactions')->name('index');
        Route::get('/add_promoaction', 'Admin\PromoactionController@getAddPromoaction')->name('add');
        Route::post('/add_promoaction_p', 'Admin\PromoactionController@addPromoaction')->name('add_p');
        Route::get('/promoaction/{promoaction_id}', 'Admin\PromoactionController@editPromoaction')->name('edit');
        Route::post('/edit/{promoaction_id}', 'Admin\PromoactionController@makePromoactionChanges')->name('edit_p');
        Route::get('/delete/{promoaction_id}', 'Admin\PromoactionController@deletePromoaction')->name('delete');
    });
    Route::prefix('users')->middleware('checkadmin')->name('users.')->group(function () {
        Route::get('/', 'Admin\UserController@getUsers')->name('index');
        Route::get('/add_user', 'Admin\UserController@getAddUser')->name('add');
        Route::post('/add_user_p', 'Admin\UserController@addUser')->name('add_p');
        Route::get('/user/{user_id}', 'Admin\UserController@editUser')->name('edit');
        Route::get('/delete/{user_id}', 'Admin\UserController@deleteUser')->name('delete');
        Route::get('/info/{user_id}', 'Admin\UserController@getUserInfo')->name('info');
        Route::post('/user/{user_id}', 'Admin\UserController@makeUserChanges')->name('edit_p');
    });
});

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $guarded = [];

    public function messages()
    {
        return $this->hasMany('App\Message');
    }

    public function client()
    {
        return $this->belongsTo('App\Client');
    }
}

app/Http/Controllers/API/TicketController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TicketController extends Controller
{
    private $set_visible_message = false;
    private $messages;


    public function getTickets()
    {
        $client = Auth::user();
        $tickets = $client->tickets;
        foreach ($tickets as $ticket) {
            $last_message = $ticket->messages()->latest()->first();
            if ($last_message) {
                $ticket->last_message = $last_message;
            } else {
                $ticket->last_message = null;
            }

        }
        $response = new ApiResponse(true, $tickets);
        return response()->json($response, 200);
    }

    public function getMessages(Request $request)
    {
        $validation = [
            'ticket_id'=>'required|exists:tickets,id'
        ];
        $check = ApiValidator::validateRequest($validation, $request);
        if ($check) {
            return response()->json($check, 200);
        }
        $data = $request->all();
        $client = Auth::user();
        $ticket = $client->tickets()->find($data['ticket_id']);
        if (!$ticket) {
            $response = new ApiResponse(false, null, 'Тикет не найден!');
            return response()->json($response, 200);
        }
        $messages = $ticket->messages;
        $this->set_visible_message = true;
        $this->messages = $messages;
        $response = new ApiResponse(true, $messages);
        return response()->json($response, 200);
    }

    public function addMessage(Request $request)
    {
        $validation = [
            'text'=>'required',
            'ticket_id'=>'required|exists:tickets,id'
        ];
        $check = ApiValidator::validateRequest($validation, $request);
        if ($check) {
            return response()->json($check, 200);
        }
        $data = $request->all();
        $client = Auth::user();
        $ticket = $client->tickets()->find($data['ticket_id']);
        if (!$ticket) {
            $response = new ApiResponse(false, null, 'Тикет не найден!');
            return response()->json($response, 200);
        }
        $message = $ticket->messages()->create([
            'text'=>$data['text']
        ]);
        $response = new ApiResponse(true, $message);
        return response()->json($response, 200);
    }

    public function addTicket(Request $request)
    {
        $validation = [
            'subject'=>'required',
            'text'=>'required'
        ];
        $check = ApiValidator::validateRequest($validation, $request);
        if ($check) {
            return response()->json($check, 200);
        }
        $data = $request->all();
        $client = Auth::user();
        $ticket = $client->tickets()->create([
            'subject'=>$data['subject'],
            'text'=>$data['text'],
        ]);
        $response = new ApiResponse(true, $ticket);
        return response()->json($response, 200);
    }

    public function __destruct()
    {
        if ($this->set_visible_message) {
            foreach ($this->messages as $message) {
                if ($message->is_admin) {
                    $message->viewed = 1;
                    $message->save();
                }
            }
        }
    }
}

app/Http/Controllers/Admin/TicketController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Ticket;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

class TicketController extends Controller
{
    public function getTickets()
    {
        $search = $this->searchTicket();
        if ($search !== 0) {
            return $search;
        }
        $title = 'Тикеты';
        $route_name = Route::currentRouteName();
        $tickets = Ticket::orderBy('id','desc')->paginate(25);
        return view('admin.tickets.list', compact('title', 'route_name', 'tickets'));
    }

    public function getTicket($ticket_id)
    {
        $title = 'Тикет '.$ticket_id;
        $route_name = Route::currentRouteName();
        $ticket = Ticket::find($ticket_id);
        $messages = $ticket->messages()->orderBy('id','desc')->paginate(20);
        return view('admin.tickets.view', compact('title', 'route_name', 'ticket','messages'));
    }

    public function sendMessage($ticket_id, Request $request)
    {
        $ticket = Ticket::find($ticket_id);
        $ticket->messages()->create([
            'is_admin'=>1,
            'text'=>$request->input('text')
        ]);
        return redirect()->back();
    }

    public function changeStatus($ticket_id, $status_id)
    {
        Ticket::find($ticket_id)->update(['status_id'=>$status_id]);
        return redirect()->back();
    }

    private function searchTicket()
    {
        if (isset($_GET['search_ticket'])) {
            $search = urldecode($_GET['search_ticket']);
            if (empty($search)) {
                $tickets = Ticket::all();
            } else {
                $tickets = Ticket::orWhere('subject', 'LIKE', "%{$search}%")
                    ->orWhere('text', 'LIKE', "%{$search}%")
                    ->orWhere('client_id', 'LIKE', "%{$search}%")->get();
            }
            return view('admin.tickets.table',compact('tickets'));
        }
        return 0;
    }
}

resources/views/admin/tickets/list.blade.php
@extends("admin.layouts.layout")
@section("content")
	<div class="container">
		<h1>Тикеты</h1>
		
		<div class="container" style="margin-top: 20px; padding: 0px;">
			<input id="search" class="form-control input-lg" type="text" placeholder="Начните вводить...">
		</div>
		<div id="search-result">
			@include("admin.tickets.table")
		</div>
		{{$tickets->links('admin.layouts.pagination')}}
	</div>
@endsection
@section("js")
	<script type="text/javascript">
        $('#search').on('input change', function (e) {
            e.preventDefault();
            $.ajax({
                url: "{{route('admin.tickets.index')}}",
                type: "GET",
                data: {search_ticket: $(this).val()},
                success: function (res) {
                    $('#search-result').html(res);
                }
            });
        });
	</script>
@endsection

resources/views/admin/tickets/table.blade.php
<table class="table">
    <thead>
    <tr>
        <th scope="col">Автор</th>
        <th scope="col">Тема</th>
        <th scope="col">Статус</th>
        <th scope="col">Дата</th>
        <th scope="col">Другое</th>
    </tr>
    </thead>
    <tbody id="search-table">
    @foreach ($tickets as $ticket)
        <tr>
            <td><a href="{{route('admin.clients.info',['client_id'=>$ticket->client->id])}}">
                    @if (!empty($ticket->client->username))
                        {{ $ticket->client->username }}
                    @else
                        {{ $ticket->client->id }}
                    @endif
                </a></td>
            <td><a href="{{route('admin.tickets.info',['ticket_id'=>$ticket->id])}}">{{ $ticket->subject }}</a></td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{DB::table('ticket_status')->where('id',$ticket->status_id)->first()->name}}
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        @foreach(DB::table('ticket_status')->get() as $status)
                            <li><a href="{{route('admin.tickets.changestatus',['ticket_id'=>$ticket->id, 'status_id'=>$status->id])}}">{{$status->name}}</a></li>
                        @endforeach
                    </ul>
                </div>
            </td>
            <td>{{ date('H:i d.m.Y', strtotime($ticket->created_at)) }}</td>
            <td>
                @if($ticket->messages?$ticket->messages()->where('is_admin', 1)->first():false)
                @else
                    <span class="label label-success">Тикет без ответа</span>
                @endif
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/tickets/view.blade.php
@extends("admin.layouts.layout")
@section("content")
	<div class="container">

		<h1>{{ $ticket->subject }}</h1>
		<div class="dropdown">
			<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				{{DB::table('ticket_status')->where('id',$ticket->status_id)->first()->name}}
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				@foreach(DB::table('ticket_status')->get() as $status)
					<li><a href="{{route('admin.tickets.changestatus',['ticket_id'=>$ticket->id, 'status_id'=>$status->id])}}">{{$status->name}}</a></li>
				@endforeach
			</ul>
		</div>
		<div class="row">
		  <div class="col-md-8">
		  	<p>
		  		<span class="glyphicon glyphicon-time" aria-hidden="true"></span> {{ date('H:i d.m.Y', strtotime($ticket->created_at)) }}
		  	</p>
		  	<p>
		  		<strong>Автор:</strong>
		  		<a href="{{route('admin.clients.info',['client_id'=>$ticket->client->id])}}">
		  			@if ($ticket->client->username)
							{{ $ticket->client->username }}
						@else
							{{ $ticket->client->id }}
						@endif
		  		</a>
		  	</p>
		  	<p>
		  		<strong>Сообщение:</strong><br>
		  		{{ $ticket->text }}
		  	</p>

		  	<div style="margin-top: 45px;">
		  		<h2>Сообщения тикета</h2>

		  		@if (!$ticket->messages)
		  			Сообщений нет
		  		@else
		  			@foreach ($messages as $message)
		  			<div style="margin-top: 35px;">
		  				<p>
					  		<strong>Отправитель:</strong>
							@if($message->is_admin)
								Администратор
							@else
								@if ($ticket->client->username)
									{{ $ticket->client->username }}
								@else
									{{ $ticket->client->id }}
								@endif
							@endif

					  	</p>
					  	<p>
					  		{{ $message->text }}
					  	</p>
					  </div>
		  			@endforeach
					{{$messages->links('admin.layouts.pagination')}}
		  		@endif
		  	</div>
		  </div>
		  <div class="col-md-4">
		  	<form action="{{route('admin.tickets.send_message',['ticket_id'=>$ticket->id])}}" method="POST">
				@csrf
				<div class="form-group">
				    <label for="ticket_answer">Ответить в тикет</label>
				    <textarea id="ticket_answer" class="form-control" rows="5" name="text"></textarea>
				  </div>
				  <button type="submit" class="btn btn-default">Отправить</button>
				</form>
		  </div>
		</div>
	</div>
@endsection