routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/check_command','Lock\LockController@checkCommand');
Route::post('/make_response','Lock\LockController@makeResponse')->name('make_response');
Route::post('/create_lock','Lock\LockController@createLock')->name('create_lock');
Route::post('/delete_lock','Lock\LockController@deleteLock')->name('delete_lock');
//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Admin\PagesController@index');
Route::prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/dashboard/{date?}', 'Admin\PagesController@welcome')->name('dashboard');

    Route::prefix('bikes')->name('bikes.')->group(function () {
        Route::get('/', 'Admin\BikeController@getBikes')->name('index');
        Route::get('/add_bike', 'Admin\BikeController@getAddBike')->name('add')->middleware('checkadmin');
        Route::post('/add_bike_p', 'Admin\BikeController@addBike')->name('add_p')->middleware('checkadmin');
        Route::get('/bike/{bike_id}', 'Admin\BikeController@editBike')->name('edit');
        Route::post('/edit/{bike_id}', 'Admin\BikeController@makeBikeChanges')->name('edit_p')->middleware('checkadmin');
        Route::get('/delete/{bike_id}', 'Admin\BikeController@deleteBike')->name('delete')->middleware('checkadmin');
    });
    Route::prefix('models')->middleware('checkadmin')->name('models.')->group(function () {
        Route::get('/', 'Admin\BikeModelController@getModels')->name('index');
        Route::get('/edit/{edit_id}', 'Admin\BikeModelController@editModel')->name('edit');
        Route::post('/model/{edit_id}', 'Admin\BikeModelController@makeModelChanges')->name('edit_p');
        Route::get('/add_model', 'Admin\BikeModelController@getAddModel')->name('add');
        Route::post('/add_model_p', 'Admin\BikeModelController@addModel')->name('add_p');
        Route::get('/delete/{delete_id}', 'Admin\BikeModelController@deleteModel')->name('delete');
    });
    Route::prefix('types')->middleware('checkadmin')->name('types.')->group(function () {
        Route::get('/', 'Admin\BikeTypeController@getTypes')->name('index');
        Route::get('/edit/{edit_id}', 'Admin\BikeTypeController@editType')->name('edit');
        Route::post('/type/{edit_id}', 'Admin\BikeTypeController@makeTypeChanges')->name('edit_p');
        Route::get('/add_type', 'Admin\BikeTypeController@getAddType')->name('add');
        Route::post('/add_type_p', 'Admin\BikeTypeController@addType')->name('add_p');
        Route::get('/delete/{delete_id}', 'Admin\BikeTypeController@deleteType')->name('delete');
    });
    Route::prefix('parkings')->name('parkings.')->group(function () {
        Route::get('/', 'Admin\ParkingController@getParkings')->name('index');
        Route::get('/add_parking', 'Admin\ParkingController@getAddParking')->name('add')->middleware('checkadmin');
        Route::post('/add_parking_p', 'Admin\ParkingController@addParking')->name('add_p')->middleware('checkadmin');
        Route::get('/parking/{parking_id}', 'Admin\ParkingController@editParking')->name('edit');
        Route::post('/edit/{parking_id}', 'Admin\ParkingController@makeParkingChanges')->name('edit_p')->middleware('checkadmin');
        Route::get('/delete/{parking_id}', 'Admin\ParkingController@deleteParking')->name('delete')->middleware('checkadmin');
    });
    Route::prefix('clients')->name('clients.')->group(function () {
        Route::get('/', 'Admin\ClientController@getClients')->name('index');
        Route::get('/add_client', 'Admin\ClientController@getAddClient')->name('add')->middleware('checkadmin');
        Route::post('/add_client_p', 'Admin\ClientController@addClient')->name('add_p')->middleware('checkadmin');
        Route::get('/client/{client_id}', 'Admin\ClientController@editClient')->name('edit')->middleware('checkadmin');
        Route::get('/delete/{client_id}', 'Admin\ClientController@deleteClient')->name('delete')->middleware('checkadmin');
        Route::get('/info/{client_id}', 'Admin\ClientController@getClientInfo')->name('info');
        Route::post('/client/{client_id}', 'Admin\ClientController@makeClientChanges')->name('edit_p')->middleware('checkadmin');
    });
    Route::prefix('trips')->name('trips.')->group(function () {
        Route::get('/', 'Admin\TripController@getTrips')->name('index');
        Route::get('/info/{trip_id}', 'Admin\TripController@getTripInfo')->name('info');
    });
    Route::prefix('payments')->name('payments.')->group(function () {
        Route::get('/', 'Admin\PaymentController@getFinances')->name('index');
    });
    Route::prefix('tickets')->name('tickets.')->group(function () {
        Route::get('/', 'Admin\TicketController@getTickets')->name('index');
        Route::get('/ticket/{ticket_id}', 'Admin\TicketController@getTicket')->name('info');
        Route::get('/changestatus/{ticket_id}/{status_id}', 'Admin\TicketController@changeStatus')->name('changestatus');
        Route::post('/send_message/{ticket_id}', 'Admin\TicketController@sendMessage')->name('send_message');
    });
    Route::prefix('tarifs')->name('tarifs.')->middleware('checkadmin')->group(function () {
        Route::get('/', 'Admin\TarifController@getTarifs')->name('index');
        Route::post('/tarif/{tarif_id}', 'Admin\TarifController@changeTarif')->name('change');
    });
    Route::prefix('promocodes')->middleware('checkadmin')->name('promocodes.')->group(function () {
        Route::get('/add_promocode', 'Admin\PromocodeController@getCreatePromocode')->name('add');
        Route::post('/add_promocode_p', 'Admin\PromocodeController@createPromocode')->name('add_p');
    });
    Route::prefix('promoactions')->middleware('checkadmin')->name('promoactions.')->group(function () {
        Route::get('/', 'Admin\PromoactionController@getPromoactions')->name('index');
        Route::get('/add_promoaction', 'Admin\PromoactionController@getAddPromoaction')->name('add');
        Route::post('/add_promoaction_p', 'Admin\PromoactionController@addPromoaction')->name('add_p');
        Route::get('/promoaction/{promoaction_id}', 'Admin\PromoactionController@editPromoaction')->name('edit');
        Route::post('/edit/{promoaction_id}', 'Admin\PromoactionController@makePromoactionChanges')->name('edit_p');
        Route::get('/delete/{promoaction_id}', 'Admin\PromoactionController@deletePromoaction')->name('delete');
    });
    Route::prefix('users')->middleware('checkadmin')->name('users.')->group(function () {
        Route::get('/', 'Admin\UserController@getUsers')->name('index');
        Route::get('/add_user', 'Admin\UserController@getAddUser')->name('add');
        Route::post('/add_user_p', 'Admin\UserController@addUser')->name('add_p');
        Route::get('/user/{user_id}', 'Admin\UserController@editUser')->name('edit');
        Route::get('/delete/{user_id}', 'Admin\UserController@deleteUser')->name('delete');
        Route::get('/info/{user_id}', 'Admin\UserController@getUserInfo')->name('info');
        Route::post('/user/{user_id}', 'Admin\UserController@makeUserChanges')->name('edit_p');
    });
});

resources/views/admin/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/style.css')}}">
</head>
<body class="inside">
<nav class="navbar navbar-default navbar-static-top">
    <div class="container" style="width: 1250px;">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">{{\Illuminate\Support\Facades\Auth::user()->name}}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @include("admin.layouts.menu")
            </ul>
        </div>
    </div>
</nav>
@yield("content")
<script src="{{asset('js/jquery.min.js')}}"></script>
<script src="{{asset('js/popper.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>

{{--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBw2B7lsWn4yTLJ3lEYXOjDX0lrRlf-LvQ&callback=initMap"
        async defer></script>--}}
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=10f356f0-a26f-4a62-b590-3ce4832edd3a" type="text/javascript"></script>
@yield("js")
</body>
</html>{{--AIzaSyBw2B7lsWn4yTLJ3lEYXOjDX0lrRlf-LvQ--}}

resources/views/admin/layouts/menu.blade.php
<ul class="nav navbar-nav">
    <li><a href="{{route('admin.dashboard')}}" @if(strpos($route_name, "dashboard"))class="active"@endif>Dashboard</a></li>
    <li><a href="{{route('admin.bikes.index')}}" @if(strpos($route_name, "bikes") || strpos($route_name, "models") || strpos($route_name, "types"))class="active"@endif>Велосипеды</a></li>
    <li><a href="{{route('admin.parkings.index')}}" @if(strpos($route_name, "parkings"))class="active"@endif>Парковки</a></li>
    <li><a href="{{route('admin.clients.index')}}" @if(strpos($route_name, "clients"))class="active"@endif>Пользователи</a></li>
    <li><a href="{{route('admin.trips.index')}}" @if(strpos($route_name, "trips"))class="active"@endif>Поездки</a></li>
    <li><a href="{{route('admin.payments.index')}}" @if(strpos($route_name, "payments"))class="active"@endif>Финансы</a></li>
    <li><a href="{{route('admin.tickets.index')}}" @if(strpos($route_name, "tickets"))class="active"@endif>Тикеты</a></li>
    <li><a href="{{route('admin.promoactions.index')}}" @if(strpos($route_name, "promoactions") || strpos($route_name, "promocodes"))class="active"@endif>Промокоды</a></li>
    <li><a href="{{route('admin.tarifs.index')}}" @if(strpos($route_name, "tarifs"))class="active"@endif>Тарифы</a></li>
    <li class="lower"> <form id="logout-form" action="{{route('logout')}}" method="post">@csrf</form><a href="{{ route('logout') }}" onclick="
        event.preventDefault();
        document.getElementById('logout-form').submit();">Выход</a></li>
</ul>

resources/views/admin/layouts/pagination.blade.php
<div class="tools">
    @if ($paginator->hasPages())
        <ul class="pagination">
            {{-- Pagination Elements --}}
            @foreach ($elements as $element)
                {{-- "Three Dots" Separator --}}
                @if (is_string($element))
                    <li><a href="#">{{ $element }}</a></li>
                @endif
                {{-- Array Of Links --}}
                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <li ><a class="active" href="#">{{ $page }}</a></li>
                        @else
                            <li><a href="{{ $url }}">{{ $page }}</a></li>
                        @endif
                    @endforeach
                @endif
            @endforeach
        </ul>
    @endif
</div>